services:
  padel-web-prod:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - "UID=${UID}"
        - "GID=${GID}"
        - "MODE=PROD"
        - "FLASK_DEBUG=0"
    ports:
      - '80:8000'
    env_file: .env
    restart: unless-stopped
  padel-web-dev:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - "UID=${UID}"
        - "GID=${GID}"
        - "MODE=DEV"
        - "FLASK_DEBUG=1"
    ports:
      - '5000:8000'
    volumes:
      - ./src:/app
    command: [ "flask", "run", "--host=0.0.0.0", "--port=8000" ]
    env_file: .env
