services:
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: luca
      MYSQL_DATABASE: padel
    ports:
      - '3306:3306'
    restart: unless-stopped
  padel-web-prod:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - "UID=${UID}"
        - "GID=${GID}"
        - "MODE=PROD"
        - "JWT_SECRET_KEY=${JWT_SECRET_KEY}"
        - "FLASK_DEBUG=0"
    ports:
      - '80:8000'
    env_file: .env
    restart: unless-stopped
    depends_on:
      - "mysql-db"
  padel-web-dev:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - "UID=${UID}"
        - "GID=${GID}"
        - "MODE=DEV"
        - "JWT_SECRET_KEY=${JWT_SECRET_KEY}"
        - "FLASK_DEBUG=1"
    ports:
      - '5000:8000'
    volumes:
      - ./src:/app
    command: [ "flask", "run", "--host=0.0.0.0", "--port=8000" ]
    env_file: .env
    depends_on:
      - "mysql-db"