services:
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: luca
      MYSQL_DATABASE: padel
    ports:
      - '3306:3306'
    restart: unless-stopped
  create_db:
    build:
      context: ./
      dockerfile: Dockerfile.create_db
      args:
        - "UID=${UID}"
        - "GID=${GID}"
    depends_on:
      - mysql-db
  rabbitmq:
    image: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: luca
      RABBITMQ_DEFAULT_PASS: luca
    restart: unless-stopped
    depends_on:
      - "create_db"
  consumer-app:
    build:
      context: ./
      dockerfile: Dockerfile.consumer
      args:
        - "UID=${UID}"
        - "GID=${GID}"
    depends_on:
      - rabbitmq
    volumes:
      - ./src:/app
  padel-web-dev:
    build:
      context: ./
      dockerfile: Dockerfile.server
      args:
        - "UID=${UID}"
        - "GID=${GID}"
        - "MODE=DEV"
        - "JWT_SECRET_KEY=${JWT_SECRET_KEY}"
        - "FLASK_DEBUG=1"
    ports:
      - '5000:8000'
    volumes:
      - ./src:/app
    command: [ "flask", "run", "--host=0.0.0.0", "--port=8000" ]
    env_file: .env
    depends_on:
      - "create_db"
      - "rabbitmq"
      # - "consumer-app"
  padel-web-prod:
    build:
      context: ./
      dockerfile: Dockerfile.server
      args:
        - "UID=${UID}"
        - "GID=${GID}"
        - "MODE=PROD"
        - "JWT_SECRET_KEY=${JWT_SECRET_KEY}"
        - "FLASK_DEBUG=0"
    ports:
      - '80:8000'
    env_file: .env
    restart: unless-stopped
    depends_on:
      - "create_db"
      - "rabbitmq"